backend:
  name: git-gateway
  branch: main

site_url: https://dynamic-bonbon-8526fa.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  - name: "berita"
    label: "Berita Gayo"
    folder: "berita"
    create: true
    extension: "html"
    format: "frontmatter"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal Publikasi", name: "date", widget: "datetime"}
      - {label: "Gambar Utama", name: "image", widget: "image"}
      - {label: "Isi Berita", name: "body", widget: "markdown"}